### ISSUE TITLE
你好 我再测试的时候发现 配置文件不存在

### ISSUE THREAD

**Issue by huyuejingling** [zixuan-ye/SmartMatting#1]
![image](https://github.com/zixuan-ye/SmartMatting/assets/7887096/80f28d56-9548-43d7-abbd-eeb13aff0eb1)

**Comment by yuanyang1991** [comment]
😄

**Comment by zixuan-ye** [comment]
Hello, I am sorry for the late reply, and thank you for your reminder. I have added the configs.
