### ISSUE TITLE
The checkpoint has been corrupted?

### ISSUE THREAD

**Issue by SuyueLiu** [zixuan-ye/SmartMatting#4]
Hi, thanks for your nice work.
When I run app_inference.sh, I got this error:
> RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

I tried to load checkpoint directly, there was a same error.

**Comment by zixuan-ye** [comment]
Hi, I'm sorry for that. I have corrected the link, maybe you can try again.
